# Usa la imagen oficial de PHP con Apache
FROM php:8.2-apache

# Habilita módulos PHP necesarios
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copia los archivos de la API al contenedor
COPY . /var/www/html/

# Expone el puerto 80 (HTTP)
EXPOSE 80

# Permisos
RUN chown -R www-data:www-data /var/www/html \
&& chmod -R 755 /var/www/html
 