version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
       - ./app:/var/www/html
       - ./public:/var/www/html/public
       - ./app/.htaccess:/var/www/html/.htaccess
    depends_on:
      - db
      
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cooperativa
      MYSQL_USER: usuariodb
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: cooperativa_backup
    volumes:
      - ./backups:/backups   
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
