FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    mysql-client \
    cron \
 && rm -rf /var/lib/apt/lists/*

COPY backup-script.sh /usr/local/bin/backup-script.sh
RUN chmod +x /usr/local/bin/backup-script.sh

CMD ["cron", "-f"]
