version: "3.9"
services:
  # Servicio de la API de Usuarios (PHP + Apache)
  api-usuarios:
    build: ./api-usuarios  
    ports:
      - "8000:80"  # Accesible en http://localhost:8000
    volumes:
      - ./api-usuarios:/var/www/html 
    depends_on:
      - db  
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=buceo

  # Servicio de la Base de Datos (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: buceo
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Ejecuta init.sql al iniciar
      - mysql_data:/var/lib/mysql  # Persistencia de datos

volumes:
  mysql_data:  # Volumen para persistir la BD